#!/usr/bin/env bash
#
# tests/vps-acceptance.sh — the launch gate.
#
# Runs on a THROWAWAY VPS, as root, and answers the three questions a release
# has to answer before anyone is told a distribution is supported:
#
#   1. Does installing twice more change anything?  (idempotency)
#   2. Does uninstalling put the host back?         (reversal)
#   3. Is the box still on the network afterwards?  (the one that ends a job)
#
# ── Why this is a script and not a checklist ─────────────────────────────────
# A VPN teardown touches NAT, routing and the firewall. The failure mode is not
# a stack trace, it is a machine that stops answering — and it is invisible to
# the person running the test, because their own session is already established
# and keeps working while every new connection is dropped. So the host is
# snapshotted before anything happens and compared byte for byte afterwards,
# and connectivity is re-probed after every single step rather than at the end.
#
# ── What it does NOT do ──────────────────────────────────────────────────────
# It does not connect a client and pass traffic. A tunnel that installs
# reversibly is not a tunnel that works, and nothing here claims otherwise:
# a green run means the host is left as it was found, not that anyone can
# connect. Client-side verification is a manual step and stays one.
#
# ── Usage ────────────────────────────────────────────────────────────────────
#   ./tests/vps-acceptance.sh --yes-destroy-this-host
#   ./tests/vps-acceptance.sh --yes-destroy-this-host --only <tag>
#   ./tests/vps-acceptance.sh --yes-destroy-this-host --out /root/acc
#
# Exit codes:  0 every check passed · 1 a check failed · 2 it could not run
#
set -uo pipefail

TESTS_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd -- "$TESTS_DIR/.." && pwd)"
INSTALLER="$REPO_DIR/vpn55.sh"

OUT_DIR="${VPN55_ACC_OUT:-/var/tmp/vpn55-acceptance}"
ONLY_TAG=""
DESTRUCTIVE=0

PASS=0
FAIL=0
WARN=0

# ─── Output ───────────────────────────────────────────────────────────────────
# Deliberately not lib/ui.sh: this file has to be runnable against a tree that
# is mid-uninstall, and a test harness that depends on the thing under test
# reports a green run when the thing under test has been deleted.
say()  { printf '\n\033[1m== %s\033[0m\n' "$*"; }
note() { printf '   %s\n' "$*"; }
ok()   { PASS=$(( PASS + 1 )); printf '   \033[32mPASS\033[0m  %s\n' "$*"; }
bad()  { FAIL=$(( FAIL + 1 )); printf '   \033[31mFAIL\033[0m  %s\n' "$*"; }
soft() { WARN=$(( WARN + 1 )); printf '   \033[33mWARN\033[0m  %s\n' "$*"; }
fatal() { printf '\n\033[31mCANNOT RUN:\033[0m %s\n' "$*" >&2; exit 2; }

# ─── Arguments ────────────────────────────────────────────────────────────────
while [ $# -gt 0 ]; do
    case "$1" in
        --yes-destroy-this-host) DESTRUCTIVE=1 ;;
        --only) ONLY_TAG="${2:-}"; shift ;;
        --out)  OUT_DIR="${2:-}";  shift ;;
        -h|--help)
            sed -n '2,32p' "$0" | sed 's/^# \{0,1\}//'
            exit 0 ;;
        *) fatal "unknown argument '$1'" ;;
    esac
    shift
done

# ─── Preflight ────────────────────────────────────────────────────────────────
[ "$(id -u)" = "0" ] || fatal "run as root."
[ -x "$INSTALLER" ] || [ -f "$INSTALLER" ] || fatal "no installer at $INSTALLER"

if [ "$DESTRUCTIVE" != "1" ]; then
    cat >&2 <<'REFUSE'
This installs and removes VPN services, rewrites NAT and firewall rules, and
restarts daemons. On a host anyone depends on, that is an outage.

Run it on a VPS you are willing to lose, and say so:

    ./tests/vps-acceptance.sh --yes-destroy-this-host
REFUSE
    exit 2
fi

for tool in ip ss awk sed sort diff; do
    command -v "$tool" >/dev/null 2>&1 || fatal "missing '$tool' — cannot snapshot this host."
done

mkdir -p "$OUT_DIR" || fatal "cannot create $OUT_DIR"
RUN_LOG="$OUT_DIR/run.log"
: > "$RUN_LOG" || fatal "cannot write $RUN_LOG"

# Unattended: every confirmation in the installer would otherwise decline,
# which would make the whole run pass by doing nothing at all.
export VPN55_ASSUME_YES=1

# ─── Host snapshot ────────────────────────────────────────────────────────────
# One directory per snapshot, one file per fact, so a diff points at WHICH fact
# changed instead of producing one unreadable blob.
#
# Volatile fields are stripped, not tolerated. Counters, PIDs, uptimes and
# handshake ages change on their own between two snapshots taken a minute apart,
# and a diff that is never empty is a diff nobody reads — which is the same as
# not having taken it.
_scrub() {
    sed -E \
        -e 's/packets [0-9]+ bytes [0-9]+/packets N bytes N/g' \
        -e 's/\[[0-9]+:[0-9]+\]/[N:N]/g' \
        -e 's/pid=[0-9]+/pid=N/g' \
        -e 's/users:\(\(.*\)\)/users:(SCRUBBED)/g' \
        -e 's/# Generated by .*/# Generated by SCRUBBED/' \
        -e 's/^# (Completed|Warning|Table).*/# SCRUBBED/' \
        -e 's/[0-9]{4}-[0-9]{2}-[0-9]{2}[T ][0-9]{2}:[0-9]{2}:[0-9]{2}/TIMESTAMP/g' \
        -e 's/handle [0-9]+/handle N/g'
}

_capture() {
    # _capture <snapshot dir> <name> <command…>
    local dir="$1" name="$2"
    shift 2
    { "$@" 2>/dev/null || true; } | _scrub | LC_ALL=C sort > "$dir/$name" 2>/dev/null || true
}

snapshot() {
    local label="$1" dir="$OUT_DIR/snap-$1"
    rm -rf "$dir" || true
    mkdir -p "$dir" || { bad "cannot create snapshot dir $dir"; return 1; }

    _capture "$dir" links        ip -o link show
    _capture "$dir" addrs        ip -o addr show
    _capture "$dir" routes4      ip -4 route show
    _capture "$dir" routes6      ip -6 route show
    _capture "$dir" rules        ip rule show
    _capture "$dir" sysctl       sysctl net.ipv4.ip_forward net.ipv6.conf.all.forwarding
    _capture "$dir" listeners    ss -lntup
    _capture "$dir" units_enabled systemctl list-unit-files --state=enabled --no-legend --no-pager
    _capture "$dir" units_running systemctl list-units --type=service --state=running --no-legend --no-pager

    # Firewall state, from whichever backends exist. Each is captured
    # separately: a rule that moved from one backend to another is a real
    # finding and a single merged file would hide it.
    if command -v nft >/dev/null 2>&1;         then _capture "$dir" fw_nft nft list ruleset; fi
    if command -v iptables-save >/dev/null 2>&1;  then _capture "$dir" fw_ipt  iptables-save; fi
    if command -v ip6tables-save >/dev/null 2>&1; then _capture "$dir" fw_ipt6 ip6tables-save; fi
    if command -v ufw >/dev/null 2>&1;         then _capture "$dir" fw_ufw ufw status verbose; fi
    if command -v firewall-cmd >/dev/null 2>&1;   then _capture "$dir" fw_fwd firewall-cmd --list-all-zones; fi

    # Files VPN55 is allowed to own. Names and modes only — contents change on
    # every run by design (keys, leases), and diffing them would drown the
    # signal that matters here, which is what was LEFT BEHIND.
    { find /etc/vpn55 /var/lib/vpn55 /var/log/vpn55 -printf '%M %p\n' 2>/dev/null || true; } \
        | LC_ALL=C sort > "$dir/vpn55_files" 2>/dev/null || true
    { find /etc/systemd/system -name '*vpn55*' -o -name '*.d' -type d 2>/dev/null || true; } \
        | LC_ALL=C sort > "$dir/units_files" 2>/dev/null || true

    if command -v dpkg-query >/dev/null 2>&1; then
        { dpkg-query -W -f='${binary:Package}\n' 2>/dev/null || true; } | LC_ALL=C sort > "$dir/packages"
    elif command -v rpm >/dev/null 2>&1; then
        { rpm -qa --qf '%{NAME}\n' 2>/dev/null || true; } | LC_ALL=C sort > "$dir/packages"
    elif command -v pacman >/dev/null 2>&1; then
        { pacman -Qq 2>/dev/null || true; } | LC_ALL=C sort > "$dir/packages"
    fi

    note "snapshot: $label"
    return 0
}

# diff_snapshots <a> <b> <report file> — prints nothing, returns 1 on difference
diff_snapshots() {
    local a="$OUT_DIR/snap-$1" b="$OUT_DIR/snap-$2" report="$3" rc=0 f name
    : > "$report" || return 1
    for f in "$a"/*; do
        [ -f "$f" ] || continue
        name="$(basename "$f")"
        if [ ! -f "$b/$name" ]; then
            printf '=== %s: present in %s, absent in %s\n' "$name" "$1" "$2" >> "$report"
            rc=1
            continue
        fi
        if ! diff -u "$f" "$b/$name" > /dev/null 2>&1; then
            {
                printf '=== %s\n' "$name"
                diff -u "$f" "$b/$name" | sed '1,2d'
                printf '\n'
            } >> "$report"
            rc=1
        fi
    done
    return "$rc"
}

# ─── Connectivity ─────────────────────────────────────────────────────────────
# The check that matters most, and the one a person cannot do for themselves:
# their own SSH session survives a broken firewall because it is already
# established. New connections are what stop working.
SSH_PORTS=""
connectivity() {
    local stage="$1" problems=0

    if ! ip route show default | grep -q .; then
        bad "[$stage] no default route — this host has lost its way off the network"
        problems=1
    fi

    # The listener the operator is sitting on. Recorded at baseline and required
    # ever after: a firewall rule set that drops it is the classic way a VPN
    # teardown locks everyone out, and it is silent until the next login.
    local port
    for port in $SSH_PORTS; do
        if ! ss -lnt "sport = :$port" 2>/dev/null | grep -q ":$port"; then
            bad "[$stage] nothing is listening on tcp/$port any more — the way back in is gone"
            problems=1
        fi
    done

    # Outbound reachability is a WARN, not a FAIL: a test VPS with no egress is
    # unusual but legitimate, and failing the whole run for it would train
    # people to ignore the result.
    if ! timeout 5 bash -c ': > /dev/tcp/1.1.1.1/443' 2>/dev/null; then
        soft "[$stage] no outbound TCP to 1.1.1.1:443 — check whether that is expected here"
    fi
    if command -v getent >/dev/null 2>&1 && ! getent hosts one.one.one.one >/dev/null 2>&1; then
        soft "[$stage] DNS did not resolve"
    fi

    [ "$problems" = "0" ] && ok "[$stage] host is still reachable"
    return 0
}

# ─── Adapters ─────────────────────────────────────────────────────────────────
# Enumerated from the installer, never named here. A harness with a hard-coded
# list of services is a harness that silently skips the adapter added last —
# which is the one most likely to be broken.
adapters_available() {
    "$INSTALLER" --adapters 2>/dev/null \
        | awk -F'\t' '$1 == "adapter" && $4 == "1" { print $2 }'
}
adapters_all() {
    "$INSTALLER" --adapters 2>/dev/null \
        | awk -F'\t' '$1 == "adapter" { printf "%s\t%s\n", $2, $3 }'
}

run_installer() {
    # run_installer <log name> <args…>
    local name="$1"
    shift
    local log="$OUT_DIR/$name.log"
    {
        printf '### %s : vpn55.sh %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"
    } >> "$RUN_LOG"
    if "$INSTALLER" "$@" >"$log" 2>&1; then
        cat "$log" >> "$RUN_LOG"
        return 0
    fi
    cat "$log" >> "$RUN_LOG"
    return 1
}

# ─── The run ──────────────────────────────────────────────────────────────────
say "VPN55 acceptance — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
note "tree:    $REPO_DIR"
note "output:  $OUT_DIR"

# Distribution identity, for the README matrix row this run authorises.
DISTRO_ID="unknown"; DISTRO_VER=""
if [ -r /etc/os-release ]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    DISTRO_ID="${ID:-unknown}"
    DISTRO_VER="${VERSION_ID:-}"
fi
note "host:    ${DISTRO_ID} ${DISTRO_VER} · kernel $(uname -r)"
note "version: $("$INSTALLER" --version 2>/dev/null | head -1)"

# Only the port the current session actually arrived on is load-bearing.
# Watching every listener on the box would fail the run whenever the service
# under test legitimately stops one of its own — and a check that cries wolf is
# a check that gets ignored on the run where it was right.
if [ -n "${SSH_CONNECTION:-}" ]; then
    SSH_PORTS="$(printf '%s' "$SSH_CONNECTION" | awk '{ print $4 }')"
    note "session: this run is connected on tcp/${SSH_PORTS}"
else
    SSH_PORTS=""
    soft "not in an SSH session — the lockout check has nothing to watch. Run this over SSH."
fi

say "1 · Baseline"
snapshot baseline || fatal "cannot snapshot this host"
connectivity baseline

say "2 · Static distribution checks"
# These need no VPS at all, but they belong in the same report: a release is not
# ready because the tunnels worked, it is ready when the tunnels worked AND a
# user whose network blocks the website can still install it.
if grep -rniE 'vpn55\.org' "$REPO_DIR/vpn55.sh" "$REPO_DIR/lib" "$REPO_DIR/helper" 2>/dev/null \
     | grep -vE ':[0-9]+:[[:space:]]*#' | grep -q .; then
    bad "the installer or its libraries reference the project website"
else
    ok "no dependency on the project website in vpn55.sh, lib/ or helper/"
fi
if "$INSTALLER" --version 2>/dev/null | grep -q 'source base:'; then
    ok "the source base URL is reported by --version"
else
    soft "--version does not report the source base URL"
fi

say "3 · Adapters present"
ADAPTERS="$(adapters_available)"
if [ -n "$ONLY_TAG" ]; then
    ADAPTERS="$(printf '%s\n' "$ADAPTERS" | grep -Fx "$ONLY_TAG" || true)"
    [ -n "$ADAPTERS" ] || fatal "'$ONLY_TAG' is not available on this host."
fi
adapters_all | while IFS=$'\t' read -r tag label; do
    if printf '%s\n' "$ADAPTERS" | grep -qFx "$tag"; then
        note "will test: $label ($tag)"
    else
        note "skipping:  $label ($tag) — cannot run on this host"
    fi
done
[ -n "$ADAPTERS" ] || fatal "no tunnel service can run on this host — nothing to test."

# ─── Per-adapter: install ×3, then uninstall ──────────────────────────────────
for tag in $ADAPTERS; do
    say "4 · $tag — install, three times"

    if run_installer "install-$tag-1" --install "$tag"; then
        ok "$tag installed"
    else
        bad "$tag failed to install — see $OUT_DIR/install-$tag-1.log"
        connectivity "$tag/after-failed-install"
        continue
    fi
    snapshot "install-$tag-1" || true
    connectivity "$tag/installed"

    # The second run is what a re-run of the menu does. The third is what
    # catches state that alternates rather than settles — a rule appended each
    # time, a unit re-enabled, a lease re-allocated. Two runs would show that as
    # a stable difference and call it converged.
    for pass in 2 3; do
        if run_installer "install-$tag-$pass" --install "$tag"; then
            ok "$tag re-installed (pass $pass)"
        else
            bad "$tag failed on pass $pass — an installer must be safe to re-run"
        fi
        snapshot "install-$tag-$pass" || true
        connectivity "$tag/pass-$pass"
    done

    if diff_snapshots "install-$tag-2" "install-$tag-3" "$OUT_DIR/drift-$tag.diff"; then
        ok "$tag is idempotent — passes 2 and 3 left the host identical"
    else
        bad "$tag DRIFTS between identical runs — $OUT_DIR/drift-$tag.diff"
        sed -n '1,40p' "$OUT_DIR/drift-$tag.diff" | sed 's/^/        /'
    fi
done

# ─── Uninstall ────────────────────────────────────────────────────────────────
# Reversal is checked against the ORIGINAL baseline, not against the state
# before this adapter's install. Anything else lets each adapter leave a little
# behind and calls the sum of it clean.
for tag in $ADAPTERS; do
    say "5 · $tag — uninstall"
    if run_installer "uninstall-$tag" --uninstall "$tag"; then
        ok "$tag uninstalled"
    else
        bad "$tag failed to uninstall — see $OUT_DIR/uninstall-$tag.log"
    fi
    connectivity "$tag/uninstalled"
done

say "6 · Reversal — is the host as we found it?"
snapshot final || true
connectivity final

if diff_snapshots baseline final "$OUT_DIR/residue.diff"; then
    ok "the host is byte-identical to its baseline"
else
    # Not automatically a failure. Installing packages is deliberate and
    # documented — an uninstall removes what it CONFIGURED, not what the
    # operator now has installed — so a package difference is reported and left
    # to a human, while a firewall or routing difference is not excusable and
    # fails the run on its own.
    if grep -q '^=== ' "$OUT_DIR/residue.diff"; then
        note "differences from baseline, by fact:"
        grep '^=== ' "$OUT_DIR/residue.diff" | sed 's/^/        /'
    fi
    if grep -qE '^=== (fw_|routes|rules|sysctl|links|addrs)' "$OUT_DIR/residue.diff"; then
        bad "uninstall left NETWORK state behind — $OUT_DIR/residue.diff"
    else
        soft "uninstall left non-network residue — read $OUT_DIR/residue.diff and judge each line"
    fi
    if grep -qE '^=== units_' "$OUT_DIR/residue.diff"; then
        bad "uninstall left systemd units behind — $OUT_DIR/residue.diff"
    fi
fi

# What is left under VPN55's own directories, stated plainly rather than judged.
# The user registry and the certificate authority OUTLIVE an adapter uninstall
# on purpose; a harness that called that a leak would be arguing with a
# documented decision.
if [ -s "$OUT_DIR/snap-final/vpn55_files" ]; then
    note "still present under /etc/vpn55, /var/lib/vpn55, /var/log/vpn55:"
    sed 's/^/        /' "$OUT_DIR/snap-final/vpn55_files" | head -40
    note "(the user registry and the certificate authority are meant to survive"
    note " an adapter uninstall — see vpn55.sh's 'Remove VPN55 network state')"
fi

# ─── Verdict ──────────────────────────────────────────────────────────────────
say "Result"
printf '   passed %s · failed %s · warnings %s\n' "$PASS" "$FAIL" "$WARN"
printf '   logs and snapshots: %s\n' "$OUT_DIR"

# One machine-readable line, because the point of this run is to authorise a row
# in the README's distribution matrix — and a row nobody can trace back to a run
# is a claim, not a test.
{
    printf 'vpn55-acceptance\t%s\t%s\t%s\t%s\tpass=%s\tfail=%s\twarn=%s\tadapters=%s\n' \
        "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
        "$DISTRO_ID" "${DISTRO_VER:-none}" "$(uname -r)" \
        "$PASS" "$FAIL" "$WARN" "$(printf '%s' "$ADAPTERS" | tr '\n' ',' | sed 's/,$//')"
} | tee "$OUT_DIR/result.tsv"

if [ "$FAIL" -gt 0 ]; then
    printf '\n\033[31mNOT READY\033[0m — do not claim %s %s in the README.\n' "$DISTRO_ID" "$DISTRO_VER"
    exit 1
fi
printf '\n\033[32mPASSED\033[0m — %s %s may be claimed, with this run recorded.\n' "$DISTRO_ID" "$DISTRO_VER"
exit 0
